FROM alpine AS builder

RUN apk add --no-cache \
  curl 

ARG HUGO_VERSION=0.144.2
ENV HUGO_VERSION=${HUGO_VERSION}
RUN curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz | tar xvz

# the GLIBC installation below only works up to alpine:3.18
FROM alpine:3.18

COPY --from=builder hugo /usr/local/bin/hugo

RUN set -x && \
  apk add --update wget ca-certificates libstdc++ gcompat

USER 10001
